# Generated by Django 5.0.4 on 2024-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_restore_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='publisher_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
