# Generated by Django 5.0.4 on 2024-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_user_password_restore_date_user_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_path',
            field=models.ImageField(upload_to='img/books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_path',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon_path',
            field=models.ImageField(upload_to='img/genres/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.ImageField(null=True, upload_to='img/users/'),
        ),
    ]
