# Generated by Django 5.0.4 on 2024-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_direction_remove_book_number_of_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='literary_direction',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon_path',
            field=models.ImageField(null=True, upload_to='img/genres/'),
        ),
    ]
